### PR TITLE
added INA226.h

### PR DESCRIPTION
**Pull request by LiamAljundi**

### CODE REVIEW

**Review by aentinger — CHANGES_REQUESTED** [review]
Please move the header files into `src` and possibly add a neat example within the `examples` folder.

**Comment by LiamAljundi** [comment]
> Please move the header files into `src` and possibly add a neat example within the `examples` folder.

Hi @aentinger 

@Rocketct is taking care of this, I just made the pull request for him to see the missing files that we requested in the Content team

**Comment by aentinger** [comment]
Allright, I leave you to it :+1:. But keep in mind I'm getting all those emails from all those repositories for any activity so please try to make more sensible PRs altogether :pray: .

**Comment by per1234** [comment]
@LiamAljundi please answer the question asked by @Rocketct:

>those files are already inside the src folder, why do you need to move in the folder example?

**Pull request closed without merging**
